<script lang="ts">
    import { classNames } from '$lib/utils/classnames';
    import Toolbar from './ui/Toolbar.svelte';
    import Window from './ui/Window.svelte';
</script>

<div
    class={classNames(
        'checkerboard relative h-[586px] w-screen',
        'after:absolute after:inset-0 after:z-0 after:bg-gradient-to-b after:from-white after:via-[#19191C]/64 after:to-[#19191C]'
    )}
>
    <Window>
        <span slot="toolbar" class="text-[#EDEDF0]"
            >Init<span class="text-accent">_</span>Schedule</span
        >
        <div slot="window" class="grid gap-4 pt-10 px-4 pb-4 md:grid-cols-5">
            {#each Array.from({ length: 5 }) as _, i}
                <div>
                    <span
                        class="text-caption font-aeonik-fono text-secondary mb-2 block uppercase tracking-[5%]"
                        >Day {i}</span
                    >
                    <div
                        class="light flex aspect-square flex-col items-center justify-center justify-center gap-4 bg-white"
                    >
                        <svg
                            width="107"
                            height="107"
                            viewBox="0 0 107 107"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <g filter="url(#filter0_d_373_42163)">
                                <rect x="46.667" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect
                                    x="46.667"
                                    y="93.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="46.667"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="46.667"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect x="53.333" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect
                                    x="53.333"
                                    y="93.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="53.333"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="53.333"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="53.333"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect x="33.333" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect
                                    x="33.333"
                                    y="93.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="33.333"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="6.66699"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="33.333"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="33.333"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="33.333"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="6.66699"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="33.333"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="6.66699"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="33.333"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="66.667"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="66.667"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="60"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="86.667"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="60"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="86.667"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="26.667"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="73.333"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="46.667"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="60"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="60"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="60"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="86.667"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="13.333"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="40"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="53.333"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="80"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="20"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#EDEDF0"
                                />
                                <rect
                                    x="33.333"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="33.333"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="33.333"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="33.333"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="33.333"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="20"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect x="60" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect
                                    x="60"
                                    y="93.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="60"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="73.333"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="73.333"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="73.333"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="13.333"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="13.333"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="13.333"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="13.333"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="6.66699"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="6.66699"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="6.66699"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="6.66699"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="6.66699"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="6.66699"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect y="33.3333" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect y="40" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect y="46.6667" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect y="53.3333" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect y="60" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect
                                    x="80"
                                    y="13.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="80"
                                    y="80"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="80"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="80"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="86.667"
                                    y="20"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="86.667"
                                    y="73.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="86.667"
                                    y="66.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="86.667"
                                    y="26.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="86.667"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="86.667"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="93.333"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="93.333"
                                    y="40"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="93.333"
                                    y="46.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="93.333"
                                    y="53.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="93.333"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="20"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="20"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect x="40" width="6.66667" height="6.66667" fill="#FD366E" />
                                <rect
                                    x="40"
                                    y="93.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="40"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="33.333"
                                    y="6.66675"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="40"
                                    y="33.3333"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="40"
                                    y="60"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="53.333"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="60"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="26.667"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="33.333"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="20"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                                <rect
                                    x="66.667"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="73.333"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#CA2B58"
                                />
                                <rect
                                    x="40"
                                    y="86.6667"
                                    width="6.66667"
                                    height="6.66667"
                                    fill="#FD366E"
                                />
                            </g>
                            <defs>
                                <filter
                                    id="filter0_d_373_42163"
                                    x="0"
                                    y="0"
                                    width="106.667"
                                    height="106.667"
                                    filterUnits="userSpaceOnUse"
                                    color-interpolation-filters="sRGB"
                                >
                                    <feFlood flood-opacity="0" result="BackgroundImageFix" />
                                    <feColorMatrix
                                        in="SourceAlpha"
                                        type="matrix"
                                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                                        result="hardAlpha"
                                    />
                                    <feOffset dx="6.66667" dy="6.66667" />
                                    <feComposite in2="hardAlpha" operator="out" />
                                    <feColorMatrix
                                        type="matrix"
                                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.12 0"
                                    />
                                    <feBlend
                                        mode="normal"
                                        in2="BackgroundImageFix"
                                        result="effect1_dropShadow_373_42163"
                                    />
                                    <feBlend
                                        mode="normal"
                                        in="SourceGraphic"
                                        in2="effect1_dropShadow_373_42163"
                                        result="shape"
                                    />
                                </filter>
                            </defs>
                        </svg>
                        <span class="font-aeonik-fono text-primary text-base uppercase"
                            >Domains<span class="text-accent">_</span>
                        </span>
                    </div>
                </div>
            {/each}
        </div>
    </Window>
</div>

<style>
    .checkerboard {
        --color: #eeeef0;
        --size: var(--spacing-2);
        --gap: calc(var(--size) * 0.5);
        background-color: var(--color);
        background-image: repeating-linear-gradient(
                to right,
                transparent,
                transparent var(--size),
                white var(--size),
                white calc(var(--size) + var(--gap))
            ),
            repeating-linear-gradient(
                to bottom,
                transparent,
                transparent var(--size),
                white var(--size),
                white calc(var(--size) + var(--gap))
            );
    }
</style>
