apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
    name: website
spec:
    gatewayClassName: traefik
    listeners:
        - name: http
          port: 8000
          protocol: HTTP
          {{- with .Values.domain }}
          hostname: {{ . | quote }}
          {{- end }}
          allowedRoutes:
              namespaces:
                  from: Same
        - name: https
          port: 8443
          protocol: HTTPS
          {{- with .Values.domain }}
          hostname: {{ . | quote }}
          {{- end }}
          allowedRoutes:
              namespaces:
                  from: Same
          tls:
              mode: Terminate
              certificateRefs:
                  - name: gateway
                    namespace: traefik

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: website
spec:
  {{- with .Values.domain }}
  hostnames:
    - {{ . | quote }}
  {{- end }}
  parentRefs:
    - name: website
  rules:
    - backendRefs:
        - name: website
          port: 80
