name: Search Index

on:
    push:
        branches:
            - main

jobs:
    indexing:
        runs-on: ubuntu-latest
        name: Indexing
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: 'meilisearch/scrapix'
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - run: yarn
            - run: yarn start -c "$SCRAPIX_CONFIG"
              env:
                  SCRAPIX_CONFIG: ${{ secrets.SCRAPIX_CONFIG }}
