name: Search Index

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: git clone https://github.com/meilisearch/docs-scraper.git
      - run: yarn
      - run: yarn start -c '$SCRAPIX_CONFIG'
