name: Search Index

on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'meilisearch/docs-scraper'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: ls
      - run: yarn
      - run: yarn start -c '$SCRAPIX_CONFIG'
        env:
          SCRAPIX_CONFIG: ${{ secrets.SCRAPIX_CONFIG }}
