name: Large file warning

on:
    pull_request:
        branches: ['**']

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
          - uses: ppremk/lfs-warning@v3.2
            with:
              token: ${{ secrets.GITHUB_TOKEN }} # Optional
              filesizelimit: 10MB
              # exclusionPatterns: |
              #  **/*.png
